### ISSUE TITLE
Connection reset on valid HTTP response [CARROT-805]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1006]
I have a repeatable problem when HTTP connections to google desktop search on MacOS just return connection reset, whereas the same input headers passed to the server (using netcat) work just fine. So far I have been unable to diagnose the cause of this, but it looks very weird.

---
Issue: CARROT-805 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Apr 27 2011
Attachments: [CARROT-805.patch](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-805/CARROT-805.patch), [inout.zip](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-805/inout.zip)
Linked issues:
 - CARROT-792

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

in/out http stream from terminal (working).

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Full execution log from eclipse:
```
2011-04-26 23:06:53,517 DEBUG org.carrot2.util.httpclient.HttpUtils: GET: http://127.0.0.1:5283/search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100?
2011-04-26 23:06:53,826 DEBUG org.apache.http.impl.conn.SingleClientConnManager: Get connection for route HttpRoute[{}->http://127.0.0.1:5283]
2011-04-26 23:06:53,835 DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator: Connecting to /127.0.0.1:5283
2011-04-26 23:06:53,855 DEBUG org.apache.http.client.protocol.RequestAddCookies: CookieSpec selected: best-match
2011-04-26 23:06:53,868 DEBUG org.apache.http.impl.client.DefaultHttpClient: Attempt 1 to execute request
2011-04-26 23:06:53,868 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Sending request: GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,869 DEBUG org.apache.http.wire: >> "GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1[\r][\n]"
2011-04-26 23:06:53,870 DEBUG org.apache.http.wire: >> "Content-type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
2011-04-26 23:06:53,870 DEBUG org.apache.http.wire: >> "Accept-Encoding: gzip[\r][\n]"
2011-04-26 23:06:53,870 DEBUG org.apache.http.wire: >> "Host: 127.0.0.1:5283[\r][\n]"
2011-04-26 23:06:53,871 DEBUG org.apache.http.wire: >> "Connection: Keep-Alive[\r][\n]"
2011-04-26 23:06:53,871 DEBUG org.apache.http.wire: >> "User-Agent: Apache-HttpClient/4.1 (java 1.5)[\r][\n]"
2011-04-26 23:06:53,871 DEBUG org.apache.http.wire: >> "[\r][\n]"
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> Content-type: application/x-www-form-urlencoded; charset=UTF-8
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> Accept-Encoding: gzip
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> Host: 127.0.0.1:5283
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> Connection: Keep-Alive
2011-04-26 23:06:53,871 DEBUG org.apache.http.headers: >> User-Agent: Apache-HttpClient/4.1 (java 1.5)
2011-04-26 23:06:53,872 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,872 DEBUG org.apache.http.impl.client.DefaultHttpClient: Closing the connection.
2011-04-26 23:06:53,872 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,872 INFO  org.apache.http.impl.client.DefaultHttpClient: I/O exception (java.net.SocketException) caught when processing request: Connection reset
2011-04-26 23:06:53,873 DEBUG org.apache.http.impl.client.DefaultHttpClient: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:168)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:260)
	at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:115)
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:622)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.carrot2.util.httpclient.HttpUtils.doGET(HttpUtils.java:185)
	at org.carrot2.source.google.GoogleDesktopDocumentSourceTest.main(GoogleDesktopDocumentSourceTest.java:75)
2011-04-26 23:06:53,875 INFO  org.apache.http.impl.client.DefaultHttpClient: Retrying request
2011-04-26 23:06:53,875 DEBUG org.apache.http.impl.client.DefaultHttpClient: Reopening the direct connection.
2011-04-26 23:06:53,876 DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator: Connecting to /127.0.0.1:5283
2011-04-26 23:06:53,876 DEBUG org.apache.http.impl.client.DefaultHttpClient: Attempt 2 to execute request
2011-04-26 23:06:53,876 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Sending request: GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1[\r][\n]"
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "Content-type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "Accept-Encoding: gzip[\r][\n]"
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "Host: 127.0.0.1:5283[\r][\n]"
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "Connection: Keep-Alive[\r][\n]"
2011-04-26 23:06:53,876 DEBUG org.apache.http.wire: >> "User-Agent: Apache-HttpClient/4.1 (java 1.5)[\r][\n]"
2011-04-26 23:06:53,877 DEBUG org.apache.http.wire: >> "[\r][\n]"
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> Content-type: application/x-www-form-urlencoded; charset=UTF-8
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> Accept-Encoding: gzip
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> Host: 127.0.0.1:5283
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> Connection: Keep-Alive
2011-04-26 23:06:53,877 DEBUG org.apache.http.headers: >> User-Agent: Apache-HttpClient/4.1 (java 1.5)
2011-04-26 23:06:53,877 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,877 DEBUG org.apache.http.impl.client.DefaultHttpClient: Closing the connection.
2011-04-26 23:06:53,877 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,877 INFO  org.apache.http.impl.client.DefaultHttpClient: I/O exception (java.net.SocketException) caught when processing request: Connection reset
2011-04-26 23:06:53,877 DEBUG org.apache.http.impl.client.DefaultHttpClient: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:168)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:260)
	at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:115)
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:622)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.carrot2.util.httpclient.HttpUtils.doGET(HttpUtils.java:185)
	at org.carrot2.source.google.GoogleDesktopDocumentSourceTest.main(GoogleDesktopDocumentSourceTest.java:75)
2011-04-26 23:06:53,878 INFO  org.apache.http.impl.client.DefaultHttpClient: Retrying request
2011-04-26 23:06:53,878 DEBUG org.apache.http.impl.client.DefaultHttpClient: Reopening the direct connection.
2011-04-26 23:06:53,878 DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator: Connecting to /127.0.0.1:5283
2011-04-26 23:06:53,878 DEBUG org.apache.http.impl.client.DefaultHttpClient: Attempt 3 to execute request
2011-04-26 23:06:53,878 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Sending request: GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,878 DEBUG org.apache.http.wire: >> "GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "Content-type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "Accept-Encoding: gzip[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "Host: 127.0.0.1:5283[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "Connection: Keep-Alive[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "User-Agent: Apache-HttpClient/4.1 (java 1.5)[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.wire: >> "[\r][\n]"
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> Content-type: application/x-www-form-urlencoded; charset=UTF-8
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> Accept-Encoding: gzip
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> Host: 127.0.0.1:5283
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> Connection: Keep-Alive
2011-04-26 23:06:53,879 DEBUG org.apache.http.headers: >> User-Agent: Apache-HttpClient/4.1 (java 1.5)
2011-04-26 23:06:53,879 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,879 DEBUG org.apache.http.impl.client.DefaultHttpClient: Closing the connection.
2011-04-26 23:06:53,879 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,879 INFO  org.apache.http.impl.client.DefaultHttpClient: I/O exception (java.net.SocketException) caught when processing request: Connection reset
2011-04-26 23:06:53,879 DEBUG org.apache.http.impl.client.DefaultHttpClient: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:168)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:260)
	at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:115)
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:622)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.carrot2.util.httpclient.HttpUtils.doGET(HttpUtils.java:185)
	at org.carrot2.source.google.GoogleDesktopDocumentSourceTest.main(GoogleDesktopDocumentSourceTest.java:75)
2011-04-26 23:06:53,880 INFO  org.apache.http.impl.client.DefaultHttpClient: Retrying request
2011-04-26 23:06:53,880 DEBUG org.apache.http.impl.client.DefaultHttpClient: Reopening the direct connection.
2011-04-26 23:06:53,880 DEBUG org.apache.http.impl.conn.DefaultClientConnectionOperator: Connecting to /127.0.0.1:5283
2011-04-26 23:06:53,881 DEBUG org.apache.http.impl.client.DefaultHttpClient: Attempt 4 to execute request
2011-04-26 23:06:53,881 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Sending request: GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "Content-type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "Accept-Encoding: gzip[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "Host: 127.0.0.1:5283[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "Connection: Keep-Alive[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "User-Agent: Apache-HttpClient/4.1 (java 1.5)[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.wire: >> "[\r][\n]"
2011-04-26 23:06:53,881 DEBUG org.apache.http.headers: >> GET /search&s=l_8BxOoWYcDVRPvIScRqxkvlJsg&q=google&format=xml&num=100? HTTP/1.1
2011-04-26 23:06:53,881 DEBUG org.apache.http.headers: >> Content-type: application/x-www-form-urlencoded; charset=UTF-8
2011-04-26 23:06:53,881 DEBUG org.apache.http.headers: >> Accept-Encoding: gzip
2011-04-26 23:06:53,881 DEBUG org.apache.http.headers: >> Host: 127.0.0.1:5283
2011-04-26 23:06:53,882 DEBUG org.apache.http.headers: >> Connection: Keep-Alive
2011-04-26 23:06:53,882 DEBUG org.apache.http.headers: >> User-Agent: Apache-HttpClient/4.1 (java 1.5)
2011-04-26 23:06:53,882 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,882 DEBUG org.apache.http.impl.client.DefaultHttpClient: Closing the connection.
2011-04-26 23:06:53,882 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection closed
2011-04-26 23:06:53,882 DEBUG org.apache.http.impl.conn.DefaultClientConnection: Connection shut down
2011-04-26 23:06:53,882 DEBUG org.apache.http.impl.conn.SingleClientConnManager: Releasing connection org.apache.http.impl.conn.SingleClientConnManager$ConnAdapter@527736bd
Exception in thread "main" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:168)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:260)
	at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:115)
	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:98)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:252)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:247)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:219)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:298)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:622)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:454)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.carrot2.util.httpclient.HttpUtils.doGET(HttpUtils.java:185)
	at org.carrot2.source.google.GoogleDesktopDocumentSourceTest.main(GoogleDesktopDocumentSourceTest.java:75)
```

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

A simple dummy test for reproducing the problem, but no luck. Works on linux for me.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This looks very much like GDS on a mac checks what's connecting to it and rejects java connections... really, sounds incredible, but I tried pushing HTTP request that succeeds with curl via a plain socket (nothing else) and the connection is dropped right after the headers are received. Either this, or something broken on the jvm side because I _can_ connect to Mac GDS via a tunnel from another machine...

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Confirmed because the same Java code works on a mac if a double-tunnel through another IP (going back to the same mac) is set up. So it looks like GDS is imply cutting off Java clients for reasons unknown.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This applies to MacOSX. GDS rejects java access to its query API for some reason.
