### ISSUE TITLE
OpenSearch Error - java.lang.ArrayIndexOutOfBoundsException: 100 [CARROT-813]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1014]
I have an open search result that throws an exception in the carrot2
interface.  The clusters are built correctly however the documents list is
not shown at all below is the search item being returned and the error
message thrown:

I Have attached the opensearch result as an XML.

&lt;item&gt;
 &lt;title&gt;Christel NAVARRO Book 6083-10 Title: Effect of Bi... - 19/10/2010
17:31:35&lt;/title&gt;
 &lt;link&gt;http://10.25.100.56/webtop/drl/objectId/09002955817ba02e&lt;/link&gt;
 &lt;description&gt;Christel NAVARRO Book 6083-10 Title: Effect of Birc5
(Survivin) siRNA on cell proliferation in Huvec Cells, n=1. Aim: Confirm the
role of Birc5 on cell proliferation using Incucyte. H-9 H-9 H-10 H-10 H-13
H-13 smartpool smartpool Luci Luci Cell death Cell death H-9 H-10 H-13
smartpool Luci Cell death 100817: transfection Prepare 3,6ml of 10x final
concentration of Atufect01 (i.e 10mg/ml) by diluting it 1/100 in Media
without serum or antibiotics. Transfer 20ml/well of complexes to cells
containing 80ml/well of the appropriate media (final dilution 1:5) Incubate
plates at 37°C for 4h and discard complexes from cells. H-9, H-10, H-13 and
smart pool have a lot of multinuclear cells, less in luciferase and Atufect
cells. 100820: 10.30am: Perform caspase 3/7 glo assay.&lt;/description&gt;
 &lt;/item&gt;

ERROR:

java.lang.ArrayIndexOutOfBoundsException: 100
       at
com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanLiteral(XMLEntityScanner.java:1135)
       at
com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:974)
       at
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(XMLNSDocumentScannerImpl.java:460)
       at
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:277)
       at
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2747)
       at
com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
       at
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
       at
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
       at
com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:807)
       at
com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
       at
com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:107)
       at
com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1205)
       at
org.carrot2.util.xsltfilter.XSLTFilterServletResponse.processWithXslt(XSLTFilterServletResponse.java:400)
       at
org.carrot2.util.xsltfilter.XSLTFilterServletResponse.finishResponse(XSLTFilterServletResponse.java:294)
       at org.carrot2.util.xsltfilter.XSLTFilter.doFilter(XSLTFilter.java:145)
       at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
       at
com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)
       at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
       at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474)
       at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
       at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
       at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
       at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:934)
       at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404)
       at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
       at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:869)
       at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
       at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
       at org.eclipse.jetty.server.Server.handle(Server.java:346)
       at
org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:581)
       at
org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1040)
       at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:592)
       at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
       at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
       at
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:526)
       at
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:41)
       at
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528)
       at java.lang.Thread.run(Thread.java:619)

![CropperCapture[1].png](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-813/CropperCapture%5B1%5D.png)

---
Issue: CARROT-813 (migrated from JIRA), created by James Sealey, resolved May 08 2011
Attachments: [CropperCapture[1].png](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-813/CropperCapture%5B1%5D.png), [FaultyCarrotSearch.xml](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-813/FaultyCarrotSearch.xml)

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

James, can you provide an XML that shows this problem in Carrot2 format? So that it can be loaded via the XML document source directly in the workbench (see attached screenshot). The format of that XML is quite simple; search for something in the Workbench and File->Save As... the result to see what it's like.  This looks like XML parser bug, so your JVM details would also be handy.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

XML document source

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I just peeked at my own JVM and indeed – there is this strange code block in XMLEntityScanner:

```Java
            for ( i = offset; i < fCurrentEntity.position; i++) {
                fCurrentEntity.ch[i] = '\n';
                whiteSpaceLookup[whiteSpaceLen++]=i;
            }
```


with whiteSpaceLookup initialized to a hardcoded value of int[100]... Looks like a problem with the JRE-default parser. You could try to override it by using putting a newer parser version in lib/endorsed in your JVM.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This is caused by a bug in jvm-embedded xerces. Override the XSLT parser using endorsed lib folder or upgrade the JVM to a newer version.
