### ISSUE TITLE
Stack trace/ assertion error emitted to log but the test passes: context listener disposal called twice? [CARROT-875]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1075]
Repeatable, regardless of the seed. There is an AssertionError, but the test passes?

```
    [junit] Suite: org.carrot2.core.ControllerTest$CachingControllerCachingOnCommonTests
    [junit]   testContextDisposal [F4C8819B026E290F:7000774B2B7B9E43]... (output follows)
    [junit]   1> 2011-11-06 23:23:12,754 WARN  org.carrot2.core.ControllerContextImpl: Unhandled exception in context listener.
    [junit]   1> java.lang.AssertionError: 
    [junit]   1>   Unexpected method call beforeDisposal(org.carrot2.core.ControllerContextImpl@656d21f1):
    [junit]   1>     beforeDisposal(isA(org.carrot2.core.IControllerContext)): expected: 1, actual: 2
    [junit]   1> 	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:45)
    [junit]   1> 	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:73)
    [junit]   1> 	at $Proxy42.beforeDisposal(Unknown Source)
    [junit]   1> 	at org.carrot2.core.ControllerContextImpl.dispose(ControllerContextImpl.java:77)
    [junit]   1> 	at org.carrot2.core.Controller.dispose(Controller.java:419)
    [junit]   1> 	at org.carrot2.core.ControllerTestsBase.performProcessingAndDispose(ControllerTestsBase.java:155)
    [junit]   1> 	at org.carrot2.core.ControllerTestsBase.performProcessingDisposeAndVerifyMocks(ControllerTestsBase.java:164)
    [junit]   1> 	at org.carrot2.core.ControllerTestsCommon.testContextDisposal(ControllerTestsCommon.java:395)
    [junit]   1> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]   1> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit]   1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]   1> 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1153)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$7(RandomizedRunner.java:1139)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$4.evaluate(RandomizedRunner.java:599)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runWithRules(RandomizedRunner.java:604)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:542)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$6(RandomizedRunner.java:523)
    [junit]   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$3.run(RandomizedRunner.java:441)
    [junit]   1> 	at java.lang.Thread.run(Thread.java:722)
```

---
Issue: CARROT-875 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Nov 07 2011

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Invalid test: subscribes context listener in init() method which may be legitimately called multiple times (if multiple components are created).
