### ISSUE TITLE
Build failure [CARROT-974]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1171]
When executing the 'clean dist' release step I get this in Windows. Will be investigating further on tomorrow.

```Java
BUILD FAILED
c:\carrot2\carrotsearch.trunk\doc\build.xml:31: The following error occurred while executing this line:
c:\carrot2\carrotsearch.trunk\doc\build.xml:79: The following error occurred while executing this line:
c:\carrot2\carrotsearch.trunk\carrot2\doc\etc\ant\doc.xml:56: The following error occurred while executing this line:
c:\carrot2\carrotsearch.trunk\carrot2\doc\etc\ant\doc.xml:194: java.lang.IllegalArgumentException
        at sun.net.www.ParseUtil.decode(ParseUtil.java:202)
        at sun.net.www.protocol.file.Handler.openConnection(Handler.java:82)
        at sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
        at java.net.URL.openConnection(URL.java:969)
        at java.net.URL.openStream(URL.java:1035)
        at org.apache.tools.ant.types.XMLCatalog.urlLookup(XMLCatalog.java:778)
        at org.apache.tools.ant.types.XMLCatalog.access$300(XMLCatalog.java:120)
        at org.apache.tools.ant.types.XMLCatalog$InternalResolver.resolveEntity(XMLCatalog.java:839)
        at org.apache.tools.ant.types.XMLCatalog.resolveEntity(XMLCatalog.java:391)
        at org.apache.xerces.util.EntityResolverWrapper.resolveEntity(Unknown Source)
        at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
```

---
Issue: CARROT-974 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Nov 21 2012

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Wrong substitution of an env. variable.
