### ISSUE TITLE
Binding exception in Workbench when changing Lucene Analyzer input attribute [CARROT-1026]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1223]
To reproduce the issue you'll need to change the Analyzer input attribute to some other value and then back to the StandardAnalyzer and then run the search. It looks like StandardAnalyzerWrapper does not get applied for some reason.

```Java
Caused by: org.carrot2.util.attribute.AttributeBindingException: Could not get field value org.carrot2.source.lucene.LuceneDocumentSource#analyzer
	at org.carrot2.util.attribute.AttributeBindingException.createWithNoKey(AttributeBindingException.java:69)
	at org.carrot2.util.attribute.AttributeBinder.bind(AttributeBinder.java:322)
	at org.carrot2.util.attribute.AttributeBinder.bind(AttributeBinder.java:209)
	at org.carrot2.util.attribute.AttributeBinder.set(AttributeBinder.java:139)
	at org.carrot2.util.attribute.AttributeBinder.set(AttributeBinder.java:115)
	at org.carrot2.util.attribute.AttributeBinder.set(AttributeBinder.java:104)
	... 17 more
Caused by: java.lang.InstantiationException: Could not create instance of class: org.apache.lucene.analysis.core.SimpleAnalyzer for attribute LuceneDocumentSource.analyzer: Class org.apache.lucene.analysis.core.SimpleAnalyzer must have a public parameterless constructor.
	at org.carrot2.util.attribute.AttributeBinder$AttributeBinderActionBind.performAction(AttributeBinder.java:578)
	at org.carrot2.util.attribute.AttributeBinder.bind(AttributeBinder.java:301)
```

---
Issue: CARROT-1026 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Oct 25 2013
Linked issues:
 - CARROT-1028

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Confirmed. I know where the problem is.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

The problem is that all analyzers no longer have parameterless constructor; attribute hint of:

```Java
    @ImplementingClasses(classes =
    {
        SimpleAnalyzer.class, 
        StandardAnalyzer.class, 
        WhitespaceAnalyzer.class
    }, strict = false)
```

no longer works since .class attribute will cause an instantiation failure in the binder. We have two options:
1) provide a customized editor for this attribute, with the most common analyzers,
2) remove the attribute from Workbench, but keep its definition as-is. The same thing is done with directory attribute, for example.

I think (1) is probably most appealing because it'd create an illusion that nothing has changed. Whether this attribute is really used in real life is another thing. Perhaps we should just remove it.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Let me know if this works for you. I'm not convinced we should keep this attribute in the user interface at all..

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Yep, we can remove it. The analyzer is only for querying anyway, it does not have a direct impact on clustering.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I'll do this: apply this workaround to 3.8.2, but revert it (and remove the attribute) from 3.9.0.
