### ISSUE TITLE
Dependency problem when running with Elasticsearch 1.5.2 [CARROT-1105]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1298]
After upgrading carrot2-core from version 3.9.4 to 3.10.1 I get a new exception when connecting to Elasticsearch 1.5.2. I have built a minimal Carrot2-Elasticsearch-example at https://github.com/Hocdoc/carrotElasticsearch15 to reproduce the issue.

The exception:

[error] (run-main-0) java.lang.NoSuchFieldError: LUCENE_3_6
java.lang.NoSuchFieldError: LUCENE_3_6
	at org.elasticsearch.Version.&lt;clinit&gt;(Version.java:43)
	at org.elasticsearch.client.transport.TransportClient.&lt;init&gt;(TransportClient.java:168)
	at org.elasticsearch.client.transport.TransportClient.&lt;init&gt;(TransportClient.java:115)
	at Hi$.main(helloWorld.scala:10)
	at Hi.main(helloWorld.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

---
Issue: CARROT-1105 (migrated from JIRA), created by Bernhard, resolved Jul 22 2015

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Thank you for letting us know. Note this isn't strictly a "bug". Carrot2-ES plugin needs to run with **exact** versions matching the compatibility tables given here:

https://github.com/carrot2/elasticsearch-carrot2#versions-and-compatibility

We will be looking at upgrading downstream packages (including ES plugin) soon.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I'm sorry for the delay. This isn't a problem – your example fetches conflicting Lucene dependencies from C2 and from ES; you should use ES's Lucene version only, then everything should work fine.
