### ISSUE TITLE
Unable to cluster result using Lingo algorithm after upgrade [CARROT-1109]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#1301]
I upgraded elasticsearch to version 1.6 and updated carrot2 plugin to version 1.9.0. When I fire _search_with_clusters query with Lingo algorithm, I get following error. It is same even with the provided example document. Only STC and ByUrl are working, Lingo and KMeans algorithms do not work.

[2015-08-05 03:27:35,293][DEBUG][action.search.type       ] [Alcmena] failed to reduce search
org.elasticsearch.action.search.ReduceSearchPhaseException: Failed to execute phase [fetch], [reduce] 
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.onFailure(TransportSearchQueryThenFetchAction.java:159)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.carrot2.matrix.factorization.NonnegativeMatrixFactorizationED
	at org.carrot2.matrix.factorization.NonnegativeMatrixFactorizationEDFactory.factorize(NonnegativeMatrixFactorizationEDFactory.java:26)
	at org.carrot2.text.vsm.TermDocumentMatrixReducer.reduce(TermDocumentMatrixReducer.java:105)
	at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.cluster(LingoClusteringAlgorithm.java:209)
	at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.access$000(LingoClusteringAlgorithm.java:63)
	at org.carrot2.clustering.lingo.LingoClusteringAlgorithm$1.process(LingoClusteringAlgorithm.java:177)
	at org.carrot2.text.clustering.MultilingualClustering.clusterByLanguage(MultilingualClustering.java:284)
	at org.carrot2.text.clustering.MultilingualClustering.process(MultilingualClustering.java:163)
	at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.process(LingoClusteringAlgorithm.java:170)
	at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:106)
	at org.carrot2.core.Controller.process(Controller.java:357)
	at org.carrot2.core.Controller.process(Controller.java:270)
	at org.carrot2.elasticsearch.ClusteringAction$TransportClusteringAction$1.onResponse(ClusteringAction.java:783)
	at org.carrot2.elasticsearch.ClusteringAction$TransportClusteringAction$1.onResponse(ClusteringAction.java:742)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:152)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	... 3 more

---
Issue: CARROT-1109 (migrated from JIRA), created by Pratikshya Kuinkel, resolved Aug 05 2015

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I've just tried on a clean ES 1.6.0 install, everything seems to work just fine.
