### ISSUE TITLE
Lucence index process error [CARROT-91]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#297]
Exception: java.io.IOException

Exception message: Unknown format version:-3

Stack trace:
java.io.IOException: Unknown format version:-3
	at org.apache.lucene.index.SegmentTermEnum.&lt;init&gt;(SegmentTermEnum.java:64)
	at org.apache.lucene.index.TermInfosReader.&lt;init&gt;(TermInfosReader.java:49)
	at org.apache.lucene.index.SegmentReader.initialize(SegmentReader.java:167)
	at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:140)
	at org.apache.lucene.index.SegmentReader.get(SegmentReader.java:121)
	at org.apache.lucene.index.IndexReader$1.doBody(IndexReader.java:166)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:579)
	at org.apache.lucene.index.IndexReader.open(IndexReader.java:147)
	at org.apache.lucene.index.IndexReader.open(IndexReader.java:137)
	at org.carrot2.demo.settings.LuceneSettingsDialog$1.actionPerformed(LuceneSettingsDialog.java:83)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1849)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2169)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:420)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.Component.processMouseEvent(Component.java:5488)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3126)
	at java.awt.Component.processEvent(Component.java:5253)
	at java.awt.Container.processEvent(Container.java:1966)
	at java.awt.Component.dispatchEventImpl(Component.java:3955)
	at java.awt.Container.dispatchEventImpl(Container.java:2024)
	at java.awt.Component.dispatchEvent(Component.java:3803)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4212)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3892)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3822)
	at java.awt.Container.dispatchEventImpl(Container.java:2010)
	at java.awt.Window.dispatchEventImpl(Window.java:1778)
	at java.awt.Component.dispatchEvent(Component.java:3803)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:153)
	at java.awt.Dialog$1.run(Dialog.java:517)
	at java.awt.Dialog$2.run(Dialog.java:545)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:543)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:843)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:645)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:616)
	at org.carrot2.demo.swing.SwingDemoGui$3.actionPerformed(SwingDemoGui.java:387)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1849)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2169)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:420)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:231)
	at java.awt.Component.processMouseEvent(Component.java:5488)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3126)
	at java.awt.Component.processEvent(Component.java:5253)
	at java.awt.Container.processEvent(Container.java:1966)
	at java.awt.Component.dispatchEventImpl(Component.java:3955)
	at java.awt.Container.dispatchEventImpl(Container.java:2024)
	at java.awt.Component.dispatchEvent(Component.java:3803)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4212)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3892)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3822)
	at java.awt.Container.dispatchEventImpl(Container.java:2010)
	at java.awt.Window.dispatchEventImpl(Window.java:1778)
	at java.awt.Component.dispatchEvent(Component.java:3803)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:157)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:149)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)

---
Issue: CARROT-91 (migrated from JIRA), created by ralph jiang, resolved Jul 19 2007

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Please specify:

- which release of Carrot2 you are using (stable/ trunk)
- which version of Lucene was used to create the index you are opening

Thanks

**Comment by dweiss** [comment]
Comment by ralph jiang (migrated from JIRA)

which release of Carrot2 you are using (stable/ trunk) 

trunk

which version of Lucene was used to create the index you are opening
lucence 2.2.0

i have tried using lucence 2.1.0 to build indexes, but the Demo browser also threw the same exception.

code:

Analyzer analyzer = new MMAnalyzer();
IndexWriter indexWriter = new IndexWriter(INDEX_PATH, analyzer, true);
indexWriter.setMaxFieldLength(25000);
....

Document doc = new Document();

doc.add(new Field(FieldsEnum.NEWS_ID.name(), String
					.valueOf(snew.id), Field.Store.YES, Index.UN_TOKENIZED));
doc.add(new Field(FieldsEnum.NEWS_URL.name(), snew.newsUrl,
					Field.Store.YES, Index.UN_TOKENIZED));
doc.add(new Field(FieldsEnum.NEWS_KEY.name(), snew.newsKey,
					Field.Store.YES, Index.TOKENIZED));
doc.add(new Field(FieldsEnum.NEWS_FROM.name(), snew.newsFrom,
					Field.Store.YES, Index.TOKENIZED));
doc.add(new Field(FieldsEnum.NEWS_TITLE.name(), snew.newsTitle,
					Field.Store.YES, Index.TOKENIZED,
					Field.TermVector.WITH_POSITIONS_OFFSETS));
doc.add(new Field(FieldsEnum.NEWS_SUMMARY.name(), snew.newsSummary,
					Field.Store.YES, Index.TOKENIZED,
					Field.TermVector.WITH_POSITIONS_OFFSETS));
doc.add(new Field(FieldsEnum.NEWS_BODY.name(), body,
					Field.Store.YES, Index.TOKENIZED,
					Field.TermVector.WITH_POSITIONS_OFFSETS));
doc.add(new Field(FieldsEnum.NEWS_ENGINE.name(), snew.newsEngine,
					Field.Store.YES, Index.TOKENIZED));
doc.add(new Field(FieldsEnum.NEWS_TIME.name(), snew.newsTime,
					Field.Store.YES, Index.UN_TOKENIZED));
doc.add(new Field(FieldsEnum.OBJ_ID.name(), String
					.valueOf(snew.objId), Field.Store.YES, Index.UN_TOKENIZED));

indexWriter.addDocument(doc);

....

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

I've just upgraded (in trunk) Lucene binaries to the 2.2.0 version – please check if it fixes the problem.

**Comment by dweiss** [comment]
Comment by ralph jiang (migrated from JIRA)

no exception has been threw any more thanks!

**Comment by dweiss** [comment]
Comment by ralph jiang (migrated from JIRA)

Will the demo browser project 
add jesoft's MMAnalyzer to lucence index at  org.carrot2.demo.settings.LuceneSettingsDialog's Analyzer combobox?

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Fixed in trunk.
