### ISSUE TITLE
Webstart Demo Browser from head fails to load [CARROT-110]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#316]
When I click on:

http://demo.carrot2.org/head/webstart/

the browser fails to load with the following exception:

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://demo.carrot2.org/head/webstart/deps-carrot2-demo-browser-jar/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
...

Launch file:

&lt;jnlp spec="1.0+" codebase="http://demo.carrot2.org:80/head/webstart/"&gt;
	&lt;information&gt;
		&lt;title&gt;Carrot2 Demo Application&lt;/title&gt;
		&lt;vendor&gt;Carrot2 Project (www.carrot2.org)&lt;/vendor&gt;

		&lt;homepage href="http://www.carrot2.org/" /&gt;

		&lt;description&gt;Carrot2 Demo Application&lt;/description&gt;
		&lt;description kind="short"&gt;Carrot2 Demo Application for tuning and testing purposes.&lt;/description&gt;
		&lt;description kind="tooltip"&gt;Carrot2 Demo&lt;/description&gt;

		&lt;icon href="img/carrot2-64x64.gif" width="64" height="64" /&gt;

		&lt;offline-allowed /&gt;
	&lt;/information&gt;

	&lt;resources&gt;
		&lt;j2se version="1.4+" /&gt;

	&lt;jar href="deps-carrot2-demo-browser-jar" /&gt; 
	&lt;jar href="carrot2-demo-browser.jar" /&gt; 

	&lt;jar href="lib/commons-pool-1.3.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-case-normalizer.jar" /&gt; 
	&lt;jar href="lib/demo-resources.jar" /&gt; 
	&lt;jar href="lib/looks-2.1.4.jar" /&gt; 
	&lt;jar href="lib/jaxrpc.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-etools.jar" /&gt; 
	&lt;jar href="lib/stempel-1.0-dw.jar" /&gt; 
	&lt;jar href="lib/Jama-1.0.2.jar" /&gt; 
	&lt;jar href="lib/aduna-clustermap-2006.1-resources.jar" /&gt; 
	&lt;jar href="lib/stempelator-1.0.jar" /&gt; 
	&lt;jar href="lib/carrot2-snowball-stemmers.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-yahooapi.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-striphtml.jar" /&gt; 
	&lt;jar href="lib/commons-collections-3.2.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-pubmed.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-xml.jar" /&gt; 
	&lt;jar href="lib/dom4j-1.6.1.jar" /&gt; 
	&lt;jar href="lib/colt-1.0.3-trimmed.jar" /&gt; 
	&lt;jar href="lib/wsdl4j-1.5.1.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-lingo.jar" /&gt; 
	&lt;jar href="lib/forms-1.1.0.jar" /&gt; 
	&lt;jar href="lib/axis.jar" /&gt; 
	&lt;jar href="lib/carrot2-util-tokenizer.jar" /&gt; 
	&lt;jar href="lib/format.jar" /&gt; 
	&lt;jar href="lib/commons-discovery-0.2.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-solr.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-haog.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-fuzzyants.jar" /&gt; 
	&lt;jar href="lib/carrot2-util-log4j.jar" /&gt; 
	&lt;jar href="lib/jaxen-1.1.1.jar" /&gt; 
	&lt;jar href="lib/carrot2-util-common.jar" /&gt; 
	&lt;jar href="lib/log4j-1.2.14.jar" /&gt; 
	&lt;jar href="lib/lucene-highlighter-2.0.0.jar" /&gt; 
	&lt;jar href="lib/carrot2-launcher.jar" /&gt; 
	&lt;jar href="lib/aduna-clustermap-2006.1.jar" /&gt; 
	&lt;jar href="lib/commons-logging-1.1.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-stc.jar" /&gt; 
	&lt;jar href="lib/violinstrings-1.0.2.jar" /&gt; 
	&lt;jar href="lib/commons-lang-2.1.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-lucene.jar" /&gt; 
	&lt;jar href="lib/jal.jar" /&gt; 
	&lt;jar href="lib/je-analysis-1.5.1.jar" /&gt; 
	&lt;jar href="lib/lucene-core-2.2.0.jar" /&gt; 
	&lt;jar href="lib/bsh-2.0b4.jar" /&gt; 
	&lt;jar href="lib/commons-httpclient-3.0.1.jar" /&gt; 
	&lt;jar href="lib/saaj.jar" /&gt; 
	&lt;jar href="lib/carrot2-filter-trc.jar" /&gt; 
	&lt;jar href="lib/carrot2-local-core.jar" /&gt; 
	&lt;jar href="lib/commons-codec-1.3.jar" /&gt; 
	&lt;jar href="lib/jdic.jar" /&gt; 
	&lt;jar href="lib/carrot2-input-msnapi.jar" /&gt; 
	&lt;jar href="lib/carrot2-stemmer-stempelator.jar" /&gt; 
	&lt;/resources&gt;

	&lt;resources os="Windows"&gt;
		&lt;jar href="lib/windows/jdic_stub.jar"/&gt;
		&lt;nativelib href="lib/windows/x86/jdic_native.jar"/&gt;

			&lt;/resources&gt;

	&lt;security&gt;
		&lt;all-permissions/&gt;
	&lt;/security&gt;

	&lt;application-desc main-class="org.carrot2.demo.DemoSplash"&gt;
		&lt;argument&gt;/res/browser-splash.png&lt;/argument&gt;
		&lt;argument&gt;4&lt;/argument&gt;
		&lt;argument&gt;org.carrot2.demo.DemoSwing&lt;/argument&gt;
		&lt;argument&gt;--resource&lt;/argument&gt;
	&lt;/application-desc&gt;
&lt;/jnlp&gt;

---
Issue: CARROT-110 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Aug 26 2007

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I'll take a look at this – funny, because I tested it from my local machine; maybe the PHPs differ slightly between the server and my local development machine.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Fixed in trunk.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Closing issues for the 2.1.1 release.
