### ISSUE TITLE
WorkingWithAttributeDescriptors example does not work [CARROT-149]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#355]
I get following exception:

Exception in thread "main" java.lang.RuntimeException: Could not load attribute metadata from: YahooDocumentSource.xml
	at carrot2.util.attribute.metadata.BindableDescriptorBuilder.getBindableMetadata(BindableDescriptorBuilder.java:183)
	at carrot2.util.attribute.metadata.BindableDescriptorBuilder.buildMetadataForBindableHierarchy(BindableDescriptorBuilder.java:137)
	at carrot2.util.attribute.metadata.BindableDescriptorBuilder.buildDescriptor(BindableDescriptorBuilder.java:66)
	at carrot2.util.attribute.metadata.BindableDescriptorBuilder.buildDescriptor(BindableDescriptorBuilder.java:44)
	at org.carrot2.examples.core.WorkingWithAttributeDescriptors.main(WorkingWithAttributeDescriptors.java:30)

---
Issue: CARROT-149 (migrated from JIRA), created by Urszula Krukar, resolved Feb 28 2008

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

For the time being, before you run this example, you need to run BindableMetadataXmlSerializer giving source code locations of at least carrot2-core and carrot2-souce-yahoo as parameters. There
is an Eclipse launch configuration that does just that in carrot2-util-attributes/etc/eclipse.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Actually, there's another problem with the example. After refactoring attribute code to carrot2-util-attribute, the attributes having their descriptions in AttributeNames don't get their metadata collected. I'll fix that in a second.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Fixed in trunk. Notice that the Eclipse launch configuration also got updated. To get the attribute descriptors to work properly, just run the "Update Attribute Metadata XML" configuration again and refresh all projects.
