### ISSUE TITLE
I am working on DCS, faceing problem when call a JSP page from RESTProcessorServlet.java [CARROT-199]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#405]
Hi every body,

I am planning to explore DCS output on a JSP page, so right now I have a simple JSP just for test named as "abc.jsp" which is coded as follows.

&lt;html&gt;
	&lt;head&gt;&lt;title&gt;Hello World JSP Page.&lt;/title&gt;&lt;/head&gt;
	&lt;body&gt;
		&lt;h3&gt;Hellow World&lt;/h3&gt;
	&lt;/body&gt;
&lt;/html&gt;

When I am trying to call this jsp from RESTProcessorServlet by adding the following call 
method 

private void callNextPage(HttpServletRequest request, HttpServletResponse response) throws ServletException
 {
	try
	{
	response.setContentType("text/html");
	getServletContext().getRequestDispatcher("/abc.jsp").forward(request, response);
	}
	catch (Exception e)
	{
		e.printStackTrace();
		logger.info(e);
	}
  }

At the moment when jsp try to lode it shows following error log and jsp page does not apear. Please guide me regarding to this.

javax.servlet.ServletException: org/apache/tools/ant/BuildListener
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:244)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428
)
        at org.mortbay.jetty.servlet.WebApplicationHandler.dispatch(WebApplicati
onHandler.java:473)
        at org.mortbay.jetty.servlet.Dispatcher.dispatch(Dispatcher.java:286)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:171)
        at org.carrot2.dcs.http.rest.RESTProcessorServlet.callNextPage(RESTProce
ssorServlet.java:178)
        at org.carrot2.dcs.http.rest.RESTProcessorServlet.doPost(RESTProcessorSe
rvlet.java:135)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:616)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428
)
        at org.mortbay.jetty.servlet.WebApplicationHandler.dispatch(WebApplicati
onHandler.java:473)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:5
68)
        at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
        at org.mortbay.jetty.servlet.WebApplicationContext.handle(WebApplication
Context.java:633)
        at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
        at org.mortbay.http.HttpServer.service(HttpServer.java:909)
        at org.mortbay.http.HttpConnection.service(HttpConnection.java:820)
        at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.mortbay.http.HttpConnection.handle(HttpConnection.java:837)
        at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:
245)
        at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
        at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

Thanks & Regards
Gyanendra Tripathi
tripathi151@gmail.com

---
Issue: CARROT-199 (migrated from JIRA), created by Gyanendra Tripathi, resolved Apr 05 2008

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This is not a Carrot2-related bug. Your problem is in incorrect servlet container configuration – investigate the exception on your own, please.
