### ISSUE TITLE
Widget is disposed [CARROT-210]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#415]
Workbench downloaded from: http://builds.carrot2.org/build/viewBuildArtifacts.action?buildKey=C3WORKBENCH-COMMIT&buildNumber=114
OS: Win32

1. Start Workbench
2. Run query (e.g. "test" from Yahoo)
3. Close the Workbench (not closing the results tab)
4. Start Workbench again, the previous query tab will be restored and the following exception will appear in the log:

!SESSION 2008-05-01 21:19:02.671 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_01
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=pl_PL
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.eclipse.ui.workbench 4 0 2008-05-01 21:19:14.734
!MESSAGE Widget is disposed
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:3563)
	at org.eclipse.swt.SWT.error(SWT.java:3481)
	at org.eclipse.swt.SWT.error(SWT.java:3452)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:432)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:325)
	at org.eclipse.swt.widgets.Control.getParent(Control.java:1329)
	at org.carrot2.workbench.core.ui.attributes.AttributesPage.getControl(Unknown Source)
	at org.eclipse.ui.part.Page.dispose(Page.java:70)
	at org.carrot2.workbench.core.ui.attributes.AttributesPage.dispose(Unknown Source)
	at org.carrot2.workbench.core.ui.attributes.AttributeListComponent.dispose(Unknown Source)
	at org.carrot2.workbench.core.ui.ResultsEditor.dispose(Unknown Source)
	at org.eclipse.ui.internal.WorkbenchPartReference.doDisposePart(WorkbenchPartReference.java:720)
	at org.eclipse.ui.internal.EditorReference.doDisposePart(EditorReference.java:306)
	at org.eclipse.ui.internal.WorkbenchPartReference.dispose(WorkbenchPartReference.java:671)
	at org.eclipse.ui.internal.WorkbenchPage.disposePart(WorkbenchPage.java:1604)
	at org.eclipse.ui.internal.WorkbenchPage.handleDeferredEvents(WorkbenchPage.java:1354)
	at org.eclipse.ui.internal.WorkbenchPage.deferUpdates(WorkbenchPage.java:1338)
	at org.eclipse.ui.internal.WorkbenchPage.closeEditors(WorkbenchPage.java:1312)
	at org.eclipse.ui.internal.WorkbenchPage.closeAllEditors(WorkbenchPage.java:1131)
	at org.eclipse.ui.internal.WorkbenchPage.dispose(WorkbenchPage.java:1653)
	at org.eclipse.ui.internal.WorkbenchWindow.closeAllPages(WorkbenchWindow.java:825)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:1559)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:699)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:675)
	at org.eclipse.ui.internal.WorkbenchWindow$2.run(WorkbenchWindow.java:790)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:788)
	at org.eclipse.jface.window.WindowManager.close(WindowManager.java:109)
	at org.eclipse.ui.internal.Workbench$15.run(Workbench.java:908)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:905)
	at org.eclipse.ui.internal.Workbench.access$15(Workbench.java:834)
	at org.eclipse.ui.internal.Workbench$22.run(Workbench.java:1078)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1076)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1048)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:696)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:675)
	at org.eclipse.ui.internal.WorkbenchWindow$2.run(WorkbenchWindow.java:790)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:788)
	at org.eclipse.jface.window.Window.handleShellCloseEvent(Window.java:736)
	at org.eclipse.jface.window.Window$3.shellClosed(Window.java:682)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:91)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:66)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:938)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:962)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:947)
	at org.eclipse.swt.widgets.Decorations.closeWidget(Decorations.java:301)
	at org.eclipse.swt.widgets.Decorations.WM_CLOSE(Decorations.java:1621)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:3674)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:291)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1554)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:1753)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4351)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2260)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:3760)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:291)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1554)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:1753)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4351)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2260)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:3760)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:291)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1554)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:1753)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4351)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2265)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3291)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2389)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2353)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2219)
	at org.eclipse.ui.internal.Workbench$4.run(Workbench.java:466)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:289)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:461)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.carrot2.workbench.core.Application.start(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:169)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:106)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:76)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:363)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:508)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:447)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1173)

---
Issue: CARROT-210 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved May 05 2008

**Comment by dweiss** [comment]
Comment by Urszula Krukar (migrated from JIRA)

Fixed in trunk.
