### ISSUE TITLE
ClassCastException while selecting a cluster in the cluster view [CARROT-268]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#473]
Steps to reproduce:
1. Perform a search (use By Url algorithm)
2. Expand ta node in he clusters tree in the editor
3. Select one of the subclusters.
4. Exception occures:
java.lang.ClassCastException: org.carrot2.core.Cluster
	at org.carrot2.workbench.core.ui.clusters.ClusterTreeContentProvider.getParent(ClusterTreeContentProvider.java:22)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getParentElement(AbstractTreeViewer.java:1619)
	at org.eclipse.jface.viewers.TreeViewer.getParentElement(TreeViewer.java:594)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1546)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1548)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2393)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1683)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2783)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1639)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1095)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:392)
	at org.carrot2.workbench.core.ui.clusters.ClusterSelectionProvider.setSelection(ClusterSelectionProvider.java:107)
	at org.carrot2.workbench.core.ui.views.ClusterTreeView$1$3.selectionChanged(ClusterTreeView.java:88)
	at org.carrot2.workbench.core.ui.clusters.ClusterSelectionProvider.fireSelectionChanged(ClusterSelectionProvider.java:132)
	at org.carrot2.workbench.core.ui.clusters.ClusterSelectionProvider.access$0(ClusterSelectionProvider.java:127)
	at org.carrot2.workbench.core.ui.clusters.ClusterSelectionProvider$SelectionListener.selectionChanged(ClusterSelectionProvider.java:27)

---
Issue: CARROT-268 (migrated from JIRA), created by Urszula Krukar, resolved Jun 17 2008

**Comment by dweiss** [comment]
Comment by Urszula Krukar (migrated from JIRA)

Fixed in trunk (reimplementing of ClusterWithParent by Stachoo fixed it).
