### ISSUE TITLE
Exception when opening the Plug-in Details window from the About box [CARROT-308]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#513]
This happens only on the downloaded Workbench, runs fine from Eclipse.

1. On Windows XP, open Workbench
2. Open the About box and click Plug-in details and the following exception will be thrown:

java.lang.SecurityException: Either the manfiest file or the signature file has been tampered in this bundle: F:\download\workbench\plugins\org.eclipse.core.runtime.compatibility.registry_3.2.100.v20070316.jar
at org.eclipse.osgi.internal.verifier.SignedBundleFile.verifyManifestAndSingatureFile(SignedBundleFile.java:98)
at org.eclipse.osgi.internal.verifier.SignedBundleFile.processSigner(SignedBundleFile.java:537)
at org.eclipse.osgi.internal.verifier.SignedBundleFile.setBundleFile(SignedBundleFile.java:473)
at org.eclipse.osgi.internal.verifier.SignedBundleHook.getVerifier(SignedBundleHook.java:165)
at org.eclipse.osgi.internal.verifier.SignedBundleHook.getVerifier(SignedBundleHook.java:177)
at org.eclipse.ui.internal.about.AboutBundleData.isSigned(AboutBundleData.java:107)
at org.eclipse.ui.internal.dialogs.AboutPluginsDialog$2.run(AboutPluginsDialog.java:105)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

---
Issue: CARROT-308 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Sep 21 2008

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Seems like these JAR files indeed have incorrect signatures, mine shows:

D:\_tmp>c:\java\sun-jdk-1.6.0_06\bin\jarsigner.exe -verify org.apache.ant_1.7.0.v200706080842.jar
jarsigner: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

Perhaps they are re-packed during the build or something?

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

I think I know why this happens – it's because our feature definition declares pack="true" for certain plugins that come unpacked in the target platform definition. When these are packed, the signature is somehow mangled. I'm investigating.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Fixed in trunk.
