### ISSUE TITLE
Unable to launch Demo GUI [CARROT-373]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#578]
unable to launch GUI from link on http://project.carrot2.org/demos.html. [[ http://demo.carrot2.org/stable/webstart ]] pop up box states 'Unable to launch the application'. Details box has the following exception message:

BadFieldException[ The field &lt;icon&gt;href has an invalid value: img/carrot2-64x64.gif,img/carrot2-64x64.gif]
	at com.sun.javaws.jnl.XMLUtils.getAttributeURL(Unknown Source)
	at com.sun.javaws.jnl.XMLUtils.getRequiredURL(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat$3.visitElement(Unknown Source)
	at com.sun.javaws.jnl.XMLUtils.visitElements(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat.getIconDescs(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat.access$000(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat$1.visitElement(Unknown Source)
	at com.sun.javaws.jnl.XMLUtils.visitElements(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat.buildInformationDesc(Unknown Source)
	at com.sun.javaws.jnl.XMLFormat.parse(Unknown Source)
	at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
	at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
	at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Latest versions of Firefox and Java

![screenshot-1.jpg](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-373/screenshot-1.jpg)

---
Issue: CARROT-373 (migrated from JIRA), created by Richard Jones, resolved Aug 28 2008
Attachments: [screenshot-1.jpg](https://carrotsearch.github.io/jira-archive-public/attachments/carrot2/CARROT-373/screenshot-1.jpg)

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Hi Richard,

Thanks for the report, I think I've fixed, please try the same URL once again.

Comment for developers: Most probably, the problem was caused during the upgrade of ophelia – the PHP script that generated the Webstart descriptor did not properly calculate BASE_URL. Given that we probably won't be using Webstart for the 3.x line apps, I took the liberty of hardcoding the proper url directly on ophelia.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

We may still expose webstart launcher, actually... This shouldn't be such a problem (even with native libs). You're right though – for now the hardcoding will work fine.
