### ISSUE TITLE
Web Application generates ClassNotFound exception [CARROT-376]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#581]
Rev. 2911

What I did:
- ant clean webapp
- deployed carrot2-webapp.war in Tomcat 5.5.20
- goto http://localhost:8080/carrot2-webapp
- got following exception:

URI: /carrot2-webapp/search 

Exception: javax.xml.transform.TransformerException: Input parsing exception. 

Stack trace:
javax.xml.transform.TransformerException: Input parsing exception.
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.processWithXslt(XSLTFilterServletResponse.java:349)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.finishResponse(XSLTFilterServletResponse.java:243)
	at org.carrot2.util.xsltfilter.XSLTFilter.doFilter(XSLTFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:222)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:833)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:639)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1285)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:189)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:150)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.processWithXslt(XSLTFilterServletResponse.java:313)
	... 17 more

-----
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:189)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:150)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.processWithXslt(XSLTFilterServletResponse.java:313)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.finishResponse(XSLTFilterServletResponse.java:243)
	at org.carrot2.util.xsltfilter.XSLTFilter.doFilter(XSLTFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:222)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:833)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:639)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1285)
	at java.lang.Thread.run(Thread.java:595)

-----
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1355)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1201)
	at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:49)
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:187)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:150)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.processWithXslt(XSLTFilterServletResponse.java:313)
	at org.carrot2.util.xsltfilter.XSLTFilterServletResponse.finishResponse(XSLTFilterServletResponse.java:243)
	at org.carrot2.util.xsltfilter.XSLTFilter.doFilter(XSLTFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:222)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:833)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:639)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1285)
	at java.lang.Thread.run(Thread.java:595)

---
Issue: CARROT-376 (migrated from JIRA), created by Urszula Krukar, resolved Aug 31 2008

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

When running Tomcat 5.5 under JDK1.5, check if common/ endorsed/ xercesImpl.jar file is there. If so, remove it and try again.

**Comment by dweiss** [comment]
Comment by Urszula Krukar (migrated from JIRA)

I found no file like that. In fact, I've searched whole Tomcat directory recursively and found no xercer\* file at all. Not even in the carrot2-webapp/lib directory.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

I've just downloaded latest Tomcat 5.5.x (without jdk1.4 compatibility pack!) and the webapp runs just fine with it (I have jdk1.6, did not check with jdk1.5 though). Also the instance on ophelia (http://demo.carrot2.org/demo-3.0/search) is also running on Tomcat 5.5 without any problems.

**Comment by dweiss** [comment]
Comment by Urszula Krukar (migrated from JIRA)

I've downloaded Tomcat again and cannot reproduce this error using it. My Tomcat must've been broken somehow.
