### ISSUE TITLE
RejectedExecutionException when running all document source tests in a batch [CARROT-391]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#596]
The following exception is thrown when running all tests in a batch (also on daily builds: http://builds.carrot2.org/browse/C3INPUTS-DAILY-220). When running separate tests, everything is fine.

org.carrot2.core.ProcessingException
at org.carrot2.source.MultipageSearchEngine.runQuery(Unknown Source)
at org.carrot2.source.MultipageSearchEngine.process(Unknown Source)
at org.carrot2.source.microsoft.MicrosoftLiveDocumentSource.process(Unknown Source)
at org.carrot2.core.ControllerUtils.performProcessing(Unknown Source)
at org.carrot2.core.ControllerUtils.performProcessing(Unknown Source)
at org.carrot2.core.ControllerUtils.performProcessing(Unknown Source)
at org.carrot2.core.SimpleController.process(Unknown Source)
at org.carrot2.core.SimpleController.process(Unknown Source)
at org.carrot2.core.test.DocumentSourceTestBase.runQuery(Unknown Source)
at org.carrot2.core.test.DocumentSourceTestBase.runQuery(Unknown Source)
at org.carrot2.core.test.DocumentSourceTestBase.runQuery(Unknown Source)
at org.carrot2.core.test.QueryableDocumentSourceTestBase.runAndCheckNoResultsQuery(Unknown Source)
at org.carrot2.core.test.MultipageDocumentSourceTestBase.__CLR2_3_2kryoaz2kl(Unknown Source)
at org.carrot2.core.test.MultipageDocumentSourceTestBase.testSpeculativeMode(Unknown Source)
at org.junitext.internal.runners.AnnotationHandlingTestClassMethodsRunner$1.run(Unknown Source)
Caused by: java.util.concurrent.RejectedExecutionException
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1759)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:767)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:658)
at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:200)

---
Issue: CARROT-391 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Sep 29 2008
Linked issues:
 - CARROT-388

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Fixed in trunk.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Related to prematurely closed executors. No longer applicable after the refactoring.
