### ISSUE TITLE
StringIndexOutOfBoundsException in web application logs [CARROT-446]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#651]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -40
        at java.lang.String.substring(String.java:1938)
        at org.carrot2.webapp.util.UserAgentUtils.isModernBrowser(UserAgentUtils.java:55)
        at org.carrot2.webapp.util.UserAgentUtils.isModernBrowser(UserAgentUtils.java:35)
        at org.carrot2.webapp.QueryProcessorServlet.doGet(QueryProcessorServlet.java:158)

---
Issue: CARROT-446 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Feb 05 2009
Linked issues:
 - CARROT-451

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Closing for the 3.0.1 release.
