### ISSUE TITLE
ArrayIndexOutOfBoundsException in daily build [CARROT-465]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#670]
http://builds.carrot2.org/browse/C2HEAD-SOURCES-76/test/org.carrot2.source.xml.XmlDocumentSourceTest%3AtestRemoteUrl

```Java
org.carrot2.core.ProcessingException: Could not process query: null
	at org.carrot2.source.xml.XmlDocumentSource.process(XmlDocumentSource.java:204)
	at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:92)
	at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:135)
	at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:112)
	at org.carrot2.core.SimpleController.process(SimpleController.java:158)
	at org.carrot2.core.SimpleController.process(SimpleController.java:109)
	at org.carrot2.core.test.DocumentSourceTestBase.runQuery(DocumentSourceTestBase.java:68)
	at org.carrot2.core.test.DocumentSourceTestBase.runQuery(DocumentSourceTestBase.java:43)
	at org.carrot2.source.xml.XmlDocumentSourceTest.__CLR2_3_09sudoi5w4(XmlDocumentSourceTest.java:273)
	at org.carrot2.source.xml.XmlDocumentSourceTest.testRemoteUrl(XmlDocumentSourceTest.java:264)
	at org.junitext.internal.runners.AnnotationHandlingTestClassMethodsRunner$1.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at org.simpleframework.xml.load.Conduit.invoke(Conduit.java:222)
	at org.simpleframework.xml.load.Conduit.commit(Conduit.java:142)
	at org.simpleframework.xml.load.Schema.commit(Schema.java:160)
	at org.simpleframework.xml.load.Composite.read(Composite.java:143)
	at org.simpleframework.xml.load.Composite.read(Composite.java:116)
	at org.simpleframework.xml.load.Traverser.read(Traverser.java:71)
	at org.simpleframework.xml.load.Persister.read(Persister.java:392)
	at org.simpleframework.xml.load.Persister.read(Persister.java:374)
	at org.simpleframework.xml.load.Persister.read(Persister.java:355)
	at org.simpleframework.xml.load.Persister.read(Persister.java:337)
	at org.carrot2.core.ProcessingResult.deserialize(ProcessingResult.java:307)
	at org.carrot2.source.xml.XmlDocumentSourceHelper.loadProcessingResult(XmlDocumentSourceHelper.java:112)
	at org.carrot2.source.xml.XmlDocumentSource.process(XmlDocumentSource.java:184)
Caused by: java.lang.IndexOutOfBoundsException: Index: 53, Size: 50
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at org.carrot2.core.ProcessingResult.documentIdToReference(ProcessingResult.java:233)
	at org.carrot2.core.ProcessingResult.afterDeserialization(ProcessingResult.java:219)
```

---
Issue: CARROT-465 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Feb 25 2009

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Closing for the 3.0.1 release.
