### ISSUE TITLE
Java 1.6-classes inside the distribution. [CARROT-470]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#675]
There are classes (stax I think) that prevent Workbench from loading on JDK1.5. Do we keep 1.5 compatibility? MacOS by default comes with JDK1.5, for example...

---
Issue: CARROT-470 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Mar 02 2009

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

In fact, stax is not required for JDK 1.6, it's only required for JDK.1.5:

http://simple.sourceforge.net/download.php

This probably means that Workbench don't work with JDK 1.5 on other platforms as well (because stax is not exported)?

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Checked with this: http://code.google.com/p/versioncheck/

Seems like the problem is more complex than I thought and resides in an attempt to define an endorsed ? class QName from STAX API. The exceptions always lead to (Workbench):

Caused by: java.lang.LinkageError: Class javax/xml/namespace/QName violates loader constraints
	at org.simpleframework.xml.stream.InputAttribute.&lt;init&gt;(InputAttribute.java:80)
	at org.simpleframework.xml.stream.InputAttribute.&lt;init&gt;(InputAttribute.java:67)
	at org.simpleframework.xml.stream.InputNodeMap.put(InputNodeMap.java:110)
	at org.simpleframework.xml.stream.InputNodeMap.put(InputNodeMap.java:96)
	at org.simpleframework.xml.stream.InputNodeMap.&lt;init&gt;(InputNodeMap.java:67)
	at org.simpleframework.xml.stream.InputElement.&lt;init&gt;(InputElement.java:69)
...

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

It should work on both 1.5 and 1.6. I guess it does because all tests are running on 1.5, aren't they? The problem is caused by fiddling with class loaders in the Workbench. At least that's my guess.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Seems to be fixed by removing overlapping classes from stax-api.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Closing for the 3.0.1 release.
