### ISSUE TITLE
Missing component suite definitions. [CARROT-476]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#681]
DCS release, Ubuntu dapper and other systems.

piccolbo@cortana:\~$ java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build 1.6.0-b105)
Java HotSpot(TM) 64-Bit Server VM (build 1.6.0-b105, mixed mode)
piccolbo@cortana:\~$ cd ff-cluster/carrott/
carrot2-dcs/ workbench/   
piccolbo@cortana:\~$ cd ff-cluster/carrott/carrot2-dcs/
piccolbo@cortana:\~/ff-cluster/carrott/carrot2-dcs$ ./dcs.sh 
[INFO] Starting DCS...
[WARN] The class was null.
[WARN] failed RestProcessor
javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:437)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite:
javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: Could intialize component suite:
java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
[WARN] Failed startup of context org.mortbay.jetty.webapp.WebAppContext@30e3c624{/,jar:file:/home/piccolbo/ff-cluster/carrott/carrot2-dcs/war/carrot2-dcs.war!/}
javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:437)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite:
javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: Could intialize component suite:
java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
[INFO] DCS started, point browser to: http://localhost:8080/
  qpiccolbo@cortana:\~/ff-cluster/carrott/carrot2-dcs$ ./dcs.sh 
[INFO] Starting DCS...
[WARN] The class was null.
[WARN] failed RestProcessor
javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:437)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite:
javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: Could intialize component suite:
java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
[WARN] Failed startup of context org.mortbay.jetty.webapp.WebAppContext@44d3db51{/,jar:file:/home/piccolbo/ff-cluster/carrott/carrot2-dcs/war/carrot2-dcs.war!/}
javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:437)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: javax.servlet.ServletException: Could intialize component suite:
javax.servlet.ServletException: Could intialize component suite
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	... 18 more
[WARN] Nested in javax.servlet.ServletException: Could intialize component suite:
java.lang.NullPointerException
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:201)
	at org.carrot2.core.ProcessingComponentSuite.deserialize(ProcessingComponentSuite.java:191)
	at org.carrot2.dcs.RestProcessorServlet.init(Unknown Source)
	at javax.servlet.GenericServlet.init(GenericServlet.java:241)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:433)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:256)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:612)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:139)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.start(Unknown Source)
	at org.carrot2.dcs.DcsApp.go(Unknown Source)
	at org.carrot2.dcs.DcsApp.main(Unknown Source)
[INFO] DCS started, point browser to: http://localhost:8080/

---
Issue: CARROT-476 (migrated from JIRA), created by Antonio Piccolboni, resolved Mar 12 2009

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

For some reason component suites are not packed in the distribution.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

The stable release works. The bug has been introduced as part of the JAR split into "minimal" set of core classes – the dependencies are not bundled. I have to dash for about 6 hours; Staszek, if you can fix it before me, go ahead.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Yep, I'll take that. I'll also write some simple smoke test of the DCS distribution so that this kind errors does't happen again.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Hi Antonio,

It's fixed now in the 3.1-dev (http://download.carrot2.org/head/carrot2-dcs-3.1-dev.zip).

**Comment by dweiss** [comment]
Comment by Antonio Piccolboni (migrated from JIRA)

works here too, thanks

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Closing for the 3.0.1 release.
