### ISSUE TITLE
NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex when using advanced Lucene syntax [CARROT-608]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#813]
It looks like we need to ship memory index with Carrot2: when I try a simple query enclosed in quotes ("data mining") with the workbench, I'm getting `NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex`.

---
Issue: CARROT-608 (migrated from JIRA), created by Stanisław Osiński (@stanislawosinski), resolved Jan 05 2010

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Can you post the stack trace? It's interesting, I grepped the code for refs. and didn't find it in the core.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Ok, it's not Lucene core, it's the highligher:

```
org.carrot2.core.ProcessingException: java.lang.NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at org.carrot2.util.ExceptionUtils.wrapAs(ExceptionUtils.java:63)
at org.carrot2.core.CachingController$CachedProcessingComponent.process(CachingController.java:660)
at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:95)
at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:138)
at org.carrot2.core.CachingController.processInternal(CachingController.java:300)
at org.carrot2.core.CachingController.process(CachingController.java:260)
at org.carrot2.workbench.core.ui.SearchJob.run(SearchJob.java:75)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/index/memory/MemoryIndex
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getReaderForField(WeightedSpanTermExtractor.java:361)
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extractWeightedSpanTerms(WeightedSpanTermExtractor.java:282)
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:149)
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:111)
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTerms(WeightedSpanTermExtractor.java:414)
at org.apache.lucene.search.highlight.QueryScorer.initExtractor(QueryScorer.java:216)
at org.apache.lucene.search.highlight.QueryScorer.init(QueryScorer.java:184)
at org.apache.lucene.search.highlight.Highlighter.getBestTextFragments(Highlighter.java:226)
at org.apache.lucene.search.highlight.Highlighter.getBestFragments(Highlighter.java:184)
at org.apache.lucene.search.highlight.Highlighter.getBestFragments(Highlighter.java:160)
at org.carrot2.source.lucene.SimpleFieldMapper.map(SimpleFieldMapper.java:216)
at org.carrot2.source.lucene.LuceneDocumentSource.fetchSearchResponse(LuceneDocumentSource.java:262)
at org.carrot2.source.lucene.LuceneDocumentSource.process(LuceneDocumentSource.java:199)
at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:95)
at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:138)
at org.carrot2.core.CachingController$CachedDataFactory.createEntry(CachingController.java:808)
at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.get(SelfPopulatingCache.java:71)
at org.carrot2.core.CachingController$CachedProcessingComponent.process(CachingController.java:640)
... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.index.memory.MemoryIndex
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:489)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:405)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:393)
at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:105)
at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
... 24 more
```

**Comment by dweiss** [comment]
Comment by Justin L. (migrated from JIRA)

I'm encountering the same error. Do I need to upgrade carrot2?

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Which version are you using?
