### ISSUE TITLE
AIOOB during tests (not repeatable). [CARROT-736]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#940]
Got this during a local test run.

```
java.lang.ArrayIndexOutOfBoundsException

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
at java.util.concurrent.FutureTask.get(FutureTask.java:83)
at org.carrot2.core.test.ClusteringAlgorithmTestBase.__CLR3_0_2p3fqmrce6(ClusteringAlgorithmTestBase.java:172)
at org.carrot2.core.test.ClusteringAlgorithmTestBase.testStress(ClusteringAlgorithmTestBase.java:136)
Caused by: java.lang.ArrayIndexOutOfBoundsException
at java.lang.System.arraycopy(Native Method)
at org.carrot2.text.analysis.ExtendedWhitespaceTokenizerImpl.zzRefill(ExtendedWhitespaceTokenizerImpl.java:537)
at org.carrot2.text.analysis.ExtendedWhitespaceTokenizerImpl.getNextToken(ExtendedWhitespaceTokenizerImpl.java:754)
at org.carrot2.text.analysis.ExtendedWhitespaceTokenizer.nextToken(ExtendedWhitespaceTokenizer.java:48)
at org.carrot2.text.preprocessing.Tokenizer.tokenize(Tokenizer.java:147)
at org.carrot2.text.preprocessing.pipeline.CompletePreprocessingPipeline.preprocess(CompletePreprocessingPipeline.java:54)
at org.carrot2.text.preprocessing.pipeline.BasicPreprocessingPipeline.preprocess(BasicPreprocessingPipeline.java:92)
at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.cluster(LingoClusteringAlgorithm.java:198)
at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.access$000(LingoClusteringAlgorithm.java:43)
at org.carrot2.clustering.lingo.LingoClusteringAlgorithm$1.process(LingoClusteringAlgorithm.java:177)
at org.carrot2.text.clustering.MultilingualClustering.clusterByLanguage(MultilingualClustering.java:223)
at org.carrot2.text.clustering.MultilingualClustering.process(MultilingualClustering.java:111)
at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.process(LingoClusteringAlgorithm.java:170)
at org.carrot2.core.ControllerUtils.performProcessing(ControllerUtils.java:102)
at org.carrot2.core.Controller.process(Controller.java:287)
at org.carrot2.core.Controller.process(Controller.java:180)
at org.carrot2.core.test.ClusteringAlgorithmTestBase$1.call(ClusteringAlgorithmTestBase.java:159)
at org.carrot2.core.test.ClusteringAlgorithmTestBase$1.call(ClusteringAlgorithmTestBase.java:152)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:619)
```

---
Issue: CARROT-736 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Oct 27 2010
Linked issues:
 - LINGO-210

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Setting fix for so that the issue doesn't get lost.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This is probably the same issue. Need to review the code again.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Should be fine now, but let's see. This is an urgent fix to distribute in minor revision if it turns out to be fixing the problem (and I have a 99.9% belief I pinpointed it right).

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Out of curiosity, I checked the logs of the webapps. The exception happened twice since the introduction of the bug in version 3.3.0.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

This would happen more frequently under heavy load, but I agree that the probability is (theoretically) very slim: you needed two components to have exactly the same identity has code and one of them had to be during processing when another was binding. Still, life shows it's possible.

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

Correct, it did happen quite often in our internal stress test builds after all.
