### ISSUE TITLE
Visualizations not updating after the result is loaded. [CARROT-792]

### ISSUE THREAD

**Issue by dweiss** [carrot2/carrot2#993]
---
Issue: CARROT-792 (migrated from JIRA), created by Dawid Weiss (@dweiss), resolved Apr 11 2011
Linked issues:
 - CARROT-805

**Comment by dweiss** [comment]
Comment by Stanisław Osiński (@stanislawosinski) (migrated from JIRA)

I'm not sure if this is relevant, but when running workbench from Eclipse, I'm getting this:


```Java
2011-04-04 20:11:52,550 WARN  browser: Embedded browser error: 
org.eclipse.swt.SWTException: 'vis' is undefined
	at org.eclipse.swt.browser.WebBrowser$EvaluateFunction.function(WebBrowser.java:190)
	at org.eclipse.swt.browser.WebSite.Invoke(WebSite.java:749)
	at org.eclipse.swt.browser.WebSite$7.method6(WebSite.java:129)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:119)
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.IDispatch.Invoke(IDispatch.java:64)
	at org.eclipse.swt.ole.win32.OleAutomation.invoke(OleAutomation.java:570)
	at org.eclipse.swt.ole.win32.OleAutomation.invoke(OleAutomation.java:533)
	at org.eclipse.swt.browser.IE.execute(IE.java:1091)
	at org.eclipse.swt.browser.WebBrowser.evaluate(WebBrowser.java:404)
	at org.eclipse.swt.browser.Browser.evaluate(Browser.java:574)
	at org.carrot2.workbench.vis.FlashViewPage.doRefresh(FlashViewPage.java:234)
	at org.carrot2.workbench.vis.FlashViewPage$1.runInUIThread(FlashViewPage.java:109)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4041)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.carrot2.workbench.core.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
```


It may be the case, that the visualization hasn't yet fully initialized when Workbench starts calling its JavaScript API. The [onInitialize](http://download.carrotsearch.com/circles/demo/assets/1.2.3/optional/html/api.html#event-onInitialize) event is fired when the visualization is fully initialized.
